/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSettingSchema extends BaseModel {
  static $columns = [
    'appName',
    'createdAt',
    'faviconId',
    'id',
    'logoId',
    'privacyPolicy',
    'termsOfSale',
    'termsOfService',
    'updatedAt',
  ] as const
  $columns = AppSettingSchema.$columns
  @column()
  declare appName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare faviconId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoId: string | null
  @column()
  declare privacyPolicy: string | null
  @column()
  declare termsOfSale: string | null
  @column()
  declare termsOfService: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'id',
    'ipAddress',
    'metadata',
    'organizationId',
    'resourceId',
    'resourceType',
    'searchVector',
    'userAgent',
    'userId',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare organizationId: string | null
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string | null
  @column()
  declare searchVector: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class EmailLogSchema extends BaseModel {
  static $columns = [
    'attachmentsMetadata',
    'bounceData',
    'category',
    'clickedAt',
    'clicksCount',
    'complaintData',
    'createdAt',
    'deliveredAt',
    'errorMessage',
    'failedAt',
    'id',
    'metadata',
    'openedAt',
    'opensCount',
    'providerId',
    'recipient',
    'sentAt',
    'status',
    'subject',
    'updatedAt',
    'userId',
  ] as const
  $columns = EmailLogSchema.$columns
  @column()
  declare attachmentsMetadata: any | null
  @column()
  declare bounceData: any | null
  @column()
  declare category: string
  @column.dateTime()
  declare clickedAt: DateTime | null
  @column()
  declare clicksCount: number | null
  @column()
  declare complaintData: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare openedAt: DateTime | null
  @column()
  declare opensCount: number | null
  @column()
  declare providerId: string | null
  @column()
  declare recipient: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class EmailVerificationTokenSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'token',
    'type',
    'updatedAt',
    'userId',
    'verifiedAt',
  ] as const
  $columns = EmailVerificationTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class HealthHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'healthData', 'id', 'metricsData', 'status'] as const
  $columns = HealthHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare healthData: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metricsData: any
  @column()
  declare status: string
}

export class IntegrationSchema extends BaseModel {
  static $columns = [
    'config',
    'createdAt',
    'id',
    'isActive',
    'metadata',
    'provider',
    'updatedAt',
  ] as const
  $columns = IntegrationSchema.$columns
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare metadata: any | null
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LogSchema extends BaseModel {
  static $columns = [
    'context',
    'createdAt',
    'id',
    'ip',
    'level',
    'message',
    'method',
    'searchVector',
    'statusCode',
    'url',
    'userAgent',
    'userId',
  ] as const
  $columns = LogSchema.$columns
  @column()
  declare context: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ip: string | null
  @column()
  declare level: string
  @column()
  declare message: string
  @column()
  declare method: string | null
  @column()
  declare searchVector: string | null
  @column()
  declare statusCode: number | null
  @column()
  declare url: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class NotificationSchema extends BaseModel {
  static $columns = [
    'actions',
    'createdAt',
    'data',
    'deletedAt',
    'id',
    'messageI18N',
    'organizationId',
    'priority',
    'readAt',
    'searchVector',
    'titleI18N',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = NotificationSchema.$columns
  @column()
  declare actions: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare messageI18N: any
  @column()
  declare organizationId: string | null
  @column()
  declare priority: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare searchVector: string | null
  @column()
  declare titleI18N: any
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class OrganizationInvitationSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'invitedById',
    'organizationId',
    'role',
    'token',
    'updatedAt',
  ] as const
  $columns = OrganizationInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitedById: string
  @column()
  declare organizationId: string
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationUserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'organizationId', 'roleId', 'userId'] as const
  $columns = OrganizationUserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare roleId: string
  @column()
  declare userId: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = [
    'address',
    'createdAt',
    'descriptionI18N',
    'email',
    'id',
    'isActive',
    'logoUrl',
    'name',
    'phone',
    'searchVector',
    'siret',
    'slug',
    'updatedAt',
    'vatNumber',
    'website',
  ] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descriptionI18N: any | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare searchVector: string | null
  @column()
  declare siret: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatNumber: string | null
  @column()
  declare website: string | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'token',
    'updatedAt',
    'usedAt',
  ] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'description',
    'id',
    'name',
    'resource',
    'slug',
    'updatedAt',
  ] as const
  $columns = PermissionSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare resource: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlanSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'currency',
    'descriptionI18N',
    'featuresI18N',
    'id',
    'isActive',
    'isVisible',
    'limits',
    'nameI18N',
    'priceMonthly',
    'priceYearly',
    'pricingModel',
    'pricingTiers',
    'searchVector',
    'slug',
    'sortOrder',
    'stripePriceIdMonthly',
    'stripePriceIdYearly',
    'stripeProductId',
    'trialDays',
    'updatedAt',
  ] as const
  $columns = PlanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare descriptionI18N: any | null
  @column()
  declare featuresI18N: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isVisible: boolean
  @column()
  declare limits: any | null
  @column()
  declare nameI18N: any
  @column()
  declare priceMonthly: string
  @column()
  declare priceYearly: string
  @column()
  declare pricingModel: string
  @column()
  declare pricingTiers: any | null
  @column()
  declare searchVector: string | null
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare stripePriceIdMonthly: string | null
  @column()
  declare stripePriceIdYearly: string | null
  @column()
  declare stripeProductId: string | null
  @column()
  declare trialDays: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare permissionId: string
  @column()
  declare roleId: string
}

export class RoleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'isSystem',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = [
    'billingInterval',
    'canceledAt',
    'createdAt',
    'currency',
    'currentPeriodEnd',
    'currentPeriodStart',
    'id',
    'organizationId',
    'planId',
    'price',
    'quantity',
    'status',
    'stripeCustomerId',
    'stripePriceId',
    'stripeSubscriptionId',
    'stripeSubscriptionItemId',
    'trialEndsAt',
    'updatedAt',
    'userCount',
  ] as const
  $columns = SubscriptionSchema.$columns
  @column()
  declare billingInterval: string
  @column.dateTime()
  declare canceledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.dateTime()
  declare currentPeriodEnd: DateTime | null
  @column.dateTime()
  declare currentPeriodStart: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare planId: string
  @column()
  declare price: string
  @column()
  declare quantity: number
  @column()
  declare status: string
  @column()
  declare stripeCustomerId: string | null
  @column()
  declare stripePriceId: string | null
  @column()
  declare stripeSubscriptionId: string | null
  @column()
  declare stripeSubscriptionItemId: string | null
  @column.dateTime()
  declare trialEndsAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userCount: number
}

export class UploadSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'disk',
    'filename',
    'id',
    'metadata',
    'mimeType',
    'size',
    'storagePath',
    'updatedAt',
    'uploadableId',
    'uploadableType',
    'userId',
    'visibility',
  ] as const
  $columns = UploadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare disk: string
  @column()
  declare filename: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare mimeType: string
  @column()
  declare size: bigint | number
  @column()
  declare storagePath: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadableId: string | null
  @column()
  declare uploadableType: string | null
  @column()
  declare userId: string
  @column()
  declare visibility: string
}

export class UserNotificationPreferenceSchema extends BaseModel {
  static $columns = [
    'channel',
    'createdAt',
    'deletedAt',
    'enabled',
    'id',
    'notificationType',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserNotificationPreferenceSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notificationType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserOrganizationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'joinedAt',
    'organizationId',
    'role',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserOrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare organizationId: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'organizationId', 'permissionId', 'userId'] as const
  $columns = UserPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare permissionId: string
  @column()
  declare userId: string
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['grantedAt', 'id', 'roleSlug', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime()
  declare grantedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare roleSlug: string
  @column()
  declare userId: string
}

export class UserSessionSchema extends BaseModel {
  static $columns = [
    'browser',
    'city',
    'country',
    'createdAt',
    'deviceType',
    'endedAt',
    'id',
    'ipAddress',
    'isActive',
    'lastActivity',
    'os',
    'referrer',
    'region',
    'startedAt',
    'updatedAt',
    'userAgent',
    'userId',
    'utmCampaign',
    'utmMedium',
    'utmSource',
  ] as const
  $columns = UserSessionSchema.$columns
  @column()
  declare browser: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string | null
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastActivity: DateTime
  @column()
  declare os: string | null
  @column()
  declare referrer: string | null
  @column()
  declare region: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string
  @column()
  declare userId: string
  @column()
  declare utmCampaign: string | null
  @column()
  declare utmMedium: string | null
  @column()
  declare utmSource: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'deletedAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'googleId',
    'id',
    'newsletterEnabled',
    'password',
    'promotionalOffersEnabled',
    'searchVector',
    'tipsEnabled',
    'twoFactorBackupCodes',
    'twoFactorConfirmedAt',
    'twoFactorEnabled',
    'twoFactorSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare newsletterEnabled: boolean
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare promotionalOffersEnabled: boolean
  @column()
  declare searchVector: string | null
  @column()
  declare tipsEnabled: boolean
  @column()
  declare twoFactorBackupCodes: string | null
  @column.dateTime()
  declare twoFactorConfirmedAt: DateTime | null
  @column()
  declare twoFactorEnabled: boolean
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
